In [1]:
#Task 2 (a)
import numpy as np
even_numbers_array = np.empty((4, 50, 5))
start_value = 2000
end_value = 4000
num_elements = (end_value - start_value) // 2  
even_numbers = np.arange(start_value, end_value, 2) 
even_numbers_array.flat[:] = even_numbers[:num_elements]  

print(even_numbers_array)



[[[2000. 2002. 2004. 2006. 2008.]
  [2010. 2012. 2014. 2016. 2018.]
  [2020. 2022. 2024. 2026. 2028.]
  [2030. 2032. 2034. 2036. 2038.]
  [2040. 2042. 2044. 2046. 2048.]
  [2050. 2052. 2054. 2056. 2058.]
  [2060. 2062. 2064. 2066. 2068.]
  [2070. 2072. 2074. 2076. 2078.]
  [2080. 2082. 2084. 2086. 2088.]
  [2090. 2092. 2094. 2096. 2098.]
  [2100. 2102. 2104. 2106. 2108.]
  [2110. 2112. 2114. 2116. 2118.]
  [2120. 2122. 2124. 2126. 2128.]
  [2130. 2132. 2134. 2136. 2138.]
  [2140. 2142. 2144. 2146. 2148.]
  [2150. 2152. 2154. 2156. 2158.]
  [2160. 2162. 2164. 2166. 2168.]
  [2170. 2172. 2174. 2176. 2178.]
  [2180. 2182. 2184. 2186. 2188.]
  [2190. 2192. 2194. 2196. 2198.]
  [2200. 2202. 2204. 2206. 2208.]
  [2210. 2212. 2214. 2216. 2218.]
  [2220. 2222. 2224. 2226. 2228.]
  [2230. 2232. 2234. 2236. 2238.]
  [2240. 2242. 2244. 2246. 2248.]
  [2250. 2252. 2254. 2256. 2258.]
  [2260. 2262. 2264. 2266. 2268.]
  [2270. 2272. 2274. 2276. 2278.]
  [2280. 2282. 2284. 2286. 2288.]
  [2290. 2292.

In [3]:
#Task 2 (b)
import numpy as np

second_layer = even_numbers_array[1]  
first_two_rows = second_layer[:2]  

row_means = np.mean(first_two_rows, axis=1)

print(row_means)

[2504. 2514.]


In [11]:
#Task 2 (c)
import numpy as np
last_three_cols = even_numbers_array[:, :, -3:]
total_sum = np.sum(last_three_cols)
print(total_sum)

1800600.0


In [23]:
#Task (d)
import numpy as np
#print(even_numbers_array)
split_arrays = np.split(even_numbers_array, 4, axis=0)
print(split_arrays)

##### Re- explain 

[[[2000. 2002. 2004. 2006. 2008.]
  [2010. 2012. 2014. 2016. 2018.]
  [2020. 2022. 2024. 2026. 2028.]
  [2030. 2032. 2034. 2036. 2038.]
  [2040. 2042. 2044. 2046. 2048.]
  [2050. 2052. 2054. 2056. 2058.]
  [2060. 2062. 2064. 2066. 2068.]
  [2070. 2072. 2074. 2076. 2078.]
  [2080. 2082. 2084. 2086. 2088.]
  [2090. 2092. 2094. 2096. 2098.]
  [2100. 2102. 2104. 2106. 2108.]
  [2110. 2112. 2114. 2116. 2118.]
  [2120. 2122. 2124. 2126. 2128.]
  [2130. 2132. 2134. 2136. 2138.]
  [2140. 2142. 2144. 2146. 2148.]
  [2150. 2152. 2154. 2156. 2158.]
  [2160. 2162. 2164. 2166. 2168.]
  [2170. 2172. 2174. 2176. 2178.]
  [2180. 2182. 2184. 2186. 2188.]
  [2190. 2192. 2194. 2196. 2198.]
  [2200. 2202. 2204. 2206. 2208.]
  [2210. 2212. 2214. 2216. 2218.]
  [2220. 2222. 2224. 2226. 2228.]
  [2230. 2232. 2234. 2236. 2238.]
  [2240. 2242. 2244. 2246. 2248.]
  [2250. 2252. 2254. 2256. 2258.]
  [2260. 2262. 2264. 2266. 2268.]
  [2270. 2272. 2274. 2276. 2278.]
  [2280. 2282. 2284. 2286. 2288.]
  [2290. 2292.

In [ ]:
import numpy as np

# Create the first array with values from 20 to 60
array1 = np.linspace(20, 60, 10)

# Create the second array with values from 10 to 30
array2 = np.linspace(10, 30, 10)

# Perform element-wise addition
result = array1 + array2

print(result)